services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    stdin_open: true
    tty: true
    command: sh
